# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbdd583053ffb1587f128012aa4de444c6402fbd40fa52908cae57ae1a28671533980ed477ea3719a3a3b6b12501274b5451cddc975bae8c75e573c22bb21b7

test:
  secret_key_base: 6e8dd309805baa3e22a3ca8c9b8cd46ecd1f98c33b0fe95c5256a5d4f918ba975f3a0579e5c550bf48567d2bdd33817de9ce408d901f247dccdab96988e12539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
